### ISSUE TITLE
webpack-ui package has a vulnerable highcharts 8.2.2 library

### ISSUE THREAD

**Issue by V-vltru** [statoscope/statoscope#118]
Hello Team,

According to "statoscope/packages/webpack-ui/package.json" document, there is highcharts library version is set to "^8.0.0" (line 28).

The alert (https://security.netapp.com/advisory/ntap-20210622-0005/) requires to upgrade the version to 9.0.0

Could anybody please upgrade?

Thanks,
-Vladimir

**Comment by smelukov** [comment]
Hi! Thanks for the issue. I'll deal with it
