### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by yoadsn** [statoscope/statoscope#121]
**Describe the bug**
Seems like local and sandbox both crash with the above error as soon as clicking anything within the report.
I guess there is a babel transpilation which forgot to include the regeneratorRuntime as a dpendency?

**To Reproduce**
1. Go to `https://statoscope.tech/`
2. Load a valid stats file
3. click any chunk name

**Expected behavior**
Should not crash

**Screenshots**
![image](https://user-images.githubusercontent.com/1684709/136167174-0dbefc30-eef8-4fba-be71-102987e61093.png)

**Versions**:
 - Latest sandbox (but also locall)
 - Browser: Chrome (osx) 94.0.4606.61 (Official Build) (x86_64)
 - Webpack: N/A
 - Statoscope: 5.11.1

**Additional context**
This did not happen a week ago or so - so seems new.

**Comment by smelukov** [comment]
Thanks for the issue 🙏 
Fixed in 5.12
