### ISSUE TITLE
@statoscope/webpack-plugin does not work without packageInfoExtension.get

### ISSUE THREAD

**Issue by plesiecki** [statoscope/statoscope#127]
**Describe the bug**
 if not specify packageInfoExtension.get, webpack build fails with error:

**Expected behavior**
> TypeError: packageInfoExtension.get is not a function

Expected behavior
no error

Versions:
    Webpack: 4
    Statoscope: 5.6.2

**Comment by Saddage** [comment]
Yeah, you're right. I changed the version in package-lock, but it got overwritten anyway.

Now I'm on the latest version for sure and everything works fine. Thanks!
