### ISSUE TITLE
Show package versions

### ISSUE THREAD

**Issue by Semigradsky** [statoscope/statoscope#141]
It would be useful to see package versions. For example, if I have package copies as on the screenshot than it will be easy to understand why I have these copies.

![image](https://user-images.githubusercontent.com/1198848/142633655-a52a9574-8504-4260-88c8-d2d66370c510.png)

**Comment by smelukov** [comment]
Hello
It already shows package versions.
Are you using webpack plugin to generate a report?

![image](https://user-images.githubusercontent.com/6654581/142635168-56da7ad3-0372-4114-a1ae-e0b5dcba866f.png)

**Comment by Semigradsky** [comment]
No, I just uploaded json to https://statoscope.tech/

**Comment by smelukov** [comment]
Default webpack stats doesn't supply packages version. Please, use [@statoscope/webpack-plugin](https://github.com/statoscope/statoscope/tree/master/packages/webpack-plugin), it collects more useful data (including packages version)

**Comment by Semigradsky** [comment]
Oh, thank you. I don't know that the example of use from https://statoscope.tech/ page has any limitations. Maybe describe on that page and on README that `webpack-plugin` gives more useful data?

**Comment by smelukov** [comment]
There is a demo stats with full of data
But I think I'll add some note about default webpack a stats. Thanks

![image](https://user-images.githubusercontent.com/6654581/142652249-336dd86b-df76-4885-8911-e866540f1395.jpeg)
