### ISSUE TITLE
webpack 5 with recommended stats doesn't work correctly

### ISSUE THREAD

**Issue by chrisands** [statoscope/statoscope#143]
**Describe the bug**
When I use recommended stats settings in webpack-plugin I get errors on report screen. 

**To Reproduce**
- Add recommended stats to webpack plugin:
```
            all: false, // disable all the stats
            hash: true, // add compilation hash
            entrypoints: true, // add entrypoints stats
            chunks: true, // add chunks stats
            chunkModules: true, // add modules stats
            reasons: true, // add modules reasons stats
            assets: true, // add assets stats
            chunkOrigins: true, // add chunks origins stats (to find out which modules require a chunk)
            version: true, // add webpack version
            builtAt: true, // add build at time
            timings: true, // add timing information
            performance: true, // add info about oversized assets
            source: true, // add module sources (uses to find modules duplicates)
            nestedModules: true, // add information about modules nested in other modules (like with module concatenation)
            publicPath: true, // add public path information
```
- Build statoscope report
- Get errors

**Expected behavior**
I get the same stats as in webpack@4. 

**Screenshots**
![photo_2021-11-25 14 25 17](https://user-images.githubusercontent.com/12214583/143433571-7e88be45-f8aa-466c-bedc-018d67cc3315.jpeg)

**Versions**:
 - Node (for non-browser bug): 
 - Browser (for browser-bug): 
 - Webpack: 5.64.1
 - Statoscope: 5.18.0

**Additional context**

**Comment by meshulam** [comment]
I ran into this and was able to fix it by adding `ids: true` to the stats config: https://webpack.js.org/configuration/stats/#statsids

This setting populates the `entrypoints[].chunks` field with an array of chunk IDs.

**Comment by smelukov** [comment]
@meshulam Thank you for investigated this issue 🙏 
I'll update readme

**Comment by chrisands** [comment]
Hmm... Adding `ids` helped to resolve the issue tho stats doesn't seem valid, because all modules seem to disappear. Adding `module: true` helps to return modules number but it seems too big and the size of entrypoints, total and initial size disappear 🤔

**Comment by meshulam** [comment]
I gave up on tweaking webpack's ridiculous number of stats options and just used the `stats: 'normal'` preset. Might be best to recommend a preset in the docs, especially if the specific required options are different across webpack versions.

**Comment by Aghassi** [comment]
Even if the README is updated, the UI should let a user know that they may have to reconfigure their stats. I was very confused to find that I had no output even though this plugin worked correctly. Come to find I had to tweak my stats (which I had already tweaked for various reasons)
