### ISSUE TITLE
Web App fails to boot: Unable to handle `null` values in `<chunk>.files` Array 

### ISSUE THREAD

**Issue by SimulatedGREG** [statoscope/statoscope#158]
**Describe the bug**
I'm not sure what causes our Stats output to create a `null` value in a `chunk`'s `files` array, but the parsing logic around this breaks the entire web application.

Here's what our stats output looks like...
![image](https://user-images.githubusercontent.com/8327811/157736294-af5bbd34-cce8-4ed2-9205-0ef8e2ddc507.png)

And here's the error we get when trying to load it...
![image](https://user-images.githubusercontent.com/8327811/157735564-75dc3264-54c0-48c3-9e56-a8f61aa5435c.png)
![image](https://user-images.githubusercontent.com/8327811/157735616-4c28338f-764c-4caa-a854-6a8aa98e4ff8.png)

I was able to find this piece of logic here, https://github.com/statoscope/statoscope/blob/master/packages/webpack-model/src/handleCompilation.ts#L426. I noticed there is a `.filter(Boolean)` after the `.map`. I believe putting the `.filter` first would solve this issue.

**To Reproduce**
1. Go to https://statoscope.tech
2. Upload this stats output (this is really trimmed down for security reasons). https://gist.github.com/SimulatedGREG/97443730ff9637bcbf90151f2154af8b
3. See browser console for error.

**Expected behavior**
I'd expect to use https://statoscope.tech to load a Stats output from my `webpack` configuration.

**Versions**:
 - Node (for non-browser bug): `14.14.0`
 - Webpack: `5.69.1`
 - Statoscope: `@statoscope/webpack-plugin@5.20.1`

**Comment by smelukov** [comment]
Solved in 5.22 ☺️
