### ISSUE TITLE
Chunks which are not used in an entry point are appearing in the Assets list for it and are being included in the entry-download-size-limits validation

### ISSUE THREAD

**Issue by hyshka** [statoscope/statoscope#168]
**Describe the bug**
I recently added the Statoscope CLI to my project to perform validation in bundle sizes. It's awesome and I am enjoying the tool, however, upon optimizing some of my entry points I noticed weird behavior.

When changing imports to dynamic imports within one entry point, the module I'm importing gets added to the list of Assets for every other entry point which doesn't use or import the module. This throws off my `entry-download-size-limits` validation rule and is visible within the Statoscope HTML report. However, when checking the stats file for some of the other entry points, I don't see the asset there, nor is it loaded when actually running the application.

I am not sure if this is a bug or if something is up with my configuration but I haven't been able to figure this out on my end so any discussion around this could be helpful!

**To Reproduce**
1. Setup multiple entry points
2. Have one with no imports
3. Have another with multiple imports, including dynamic imports to generate async chunks
4. Observe that async chunks are included in the `entry-download-size-limits` validation rule and as Assets for the entry point with no imports

**Expected behavior**
For my use case, I would expect only the chunks or assets that are required for a particular entry point to be included in the calculations and lists in the UI.

**Screenshots**

Stats file:
![image](https://user-images.githubusercontent.com/2090758/175575105-568672cb-a992-4033-83d1-bbd5aef98dd6.png)

Statoscope UI:
This entry point actually only requires two of the chunks shown here, Statoscope seems to be pulling in the other initial and async chunks incorrectly.
![image](https://user-images.githubusercontent.com/2090758/175575193-21d2b2ad-26f0-4207-bca7-67ae295882c1.png)

Statoscope CLI validation:
![image](https://user-images.githubusercontent.com/2090758/175575675-3fa1687e-9fa6-46fa-8ca3-fe98d8be8fbf.png)

**Versions**:
 - Node (for non-browser bug): 
 - Browser (for browser-bug): 
 - Webpack: 5.73.0
 - Statoscope: 5.22.0
 
 **Addition information**:
Looking at the [entry-download-size-limits source](https://github.com/statoscope/statoscope/blob/master/packages/stats-validator-plugin-webpack/src/rules/entry-download-size-limits/index.ts#L116) it appears the default is to include all the children of each chunk with an entry point. I was able to find that my runtime chunk had a lot of children which aren't used in the entry point in question. I wonder if this is included because the runtime chunk could technically fetch any of these at some point in time.

I am currently using `optimization.runtimeChunk = "single"` in my Webpack config. Setting `optimization.runtimeChunk = false` removes the runtime chunks and their children from appearing within all entry points, but the CLI validation errors persist.

I did some testing by modifying the source for [entry-download-size-limits](https://github.com/statoscope/statoscope/blob/master/packages/stats-validator-plugin-webpack/src/rules/entry-download-size-limits/index.ts#L116) and I think that adding an exclusion option for chunks would help me work around this, without trying to modify the internals of Webpack on how it reports async chunks in the runtime. This is my first time using jora, so it's pretty ugly, but it is serviceable.

```
diff --git a/packages/stats-validator-plugin-webpack/src/rules/entry-download-size-limits/index.ts b/packages/stats-validator-plugin-webpack/src/rules/entry-download-size-limits/index.ts
index 476b200..901c5fc 100644
--- a/packages/stats-validator-plugin-webpack/src/rules/entry-download-size-limits/index.ts
+++ b/packages/stats-validator-plugin-webpack/src/rules/entry-download-size-limits/index.ts
@@ -16,7 +16,7 @@ export type Limits = {
   maxAsyncSize?: number;
 };

-export type RuleExcludeItem = ExcludeItem<'compilation' | 'entry' | 'asset'>;
+export type RuleExcludeItem = ExcludeItem<'compilation' | 'entry' | 'asset' | 'chunk'>;

 export type Params = {
   exclude?: Array<string | RegExp | RuleExcludeItem>;
@@ -87,11 +87,12 @@ const entryDownloadSizeLimits: WebpackRule<Params> = (ruleParams, data, api): vo
   $input: resolveInputFile();
   $params: #.params;
   $useCompressedSize: [$params.useCompressedSize, true].useNotNullish();
+  $getChunks: => $.data.chunks.exclude({ exclude: $params.exclude.[type='chunk'].name, get: <name> }).($ + $..children);
   $getSizeByChunks: => files.exclude({
     exclude: $params.exclude.[type='asset'].name,
     get: <name>,
   }).(getAssetSize($$, $useCompressedSize!=false)).reduce(=> size + $$, 0);
-
+
   $input.compilations
   .exclude({
     exclude: $params.exclude.[type='compilation'].name,
@@ -113,13 +114,13 @@ const entryDownloadSizeLimits: WebpackRule<Params> = (ruleParams, data, api): vo
         maxInitialSize: [$matchedRule.maxInitialSize, $params.global.maxInitialSize].useNotNullish(),
         maxAsyncSize: [$matchedRule.maxAsyncSize, $params.global.maxAsyncSize].useNotNullish(),
       };
-      $chunks: ($entry.data.chunks + $entry.data.chunks..children);
+      $chunks: $entry.$getChunks();
       $initialChunks: $chunks.[initial];
       $asyncChunks: $chunks.[not initial];
       $size: $chunks.$getSizeByChunks($compilation.hash);
       $initialSize: $initialChunks.$getSizeByChunks($compilation.hash);
       $asyncSize: $asyncChunks.$getSizeByChunks($compilation.hash);
-
+
       $entry,
       $chunks,
       $initialChunks,

```

**Comment by smelukov** [comment]
@hyshka Hello! Would you provide some stats-file (obviously without source code) that reproduces this behaviour? :)
I can't reproduce this with the steps you specified :(

**Comment by hyshka** [comment]
@smelukov For that entry, it would be:
```
<script src="/static/bundles/runtime.3dd7a6382151c3421dd7.bundle.js" ></script>
<script src="/static/bundles/billing_form.ac131a2772166f40a1de.bundle.js" ></script>
```

**Comment by smelukov** [comment]
@hyshka Could you try 5.22.1-alpha.0 please?
If it'll fix your issue then I'll publish a stable version

**Comment by hyshka** [comment]
@smelukov Thank you! I just tested it and my issue with the runtime chunks children is fixed :heavy_check_mark:. However, it is still only a partial fix for me. I found now that another chunk, which is used within many modules, appears to be having its children pulled in as well. Here's an example:

These chunks in the Statocope report are incorrect:
![image](https://user-images.githubusercontent.com/2090758/177573643-b694add6-f5d8-4516-9819-608dbbd2a59e.png)

Because the entry point is only using these chunks:
![image](https://user-images.githubusercontent.com/2090758/177573747-48c2abb4-34ac-449b-849b-fc853f6e699f.png)

However, two of them `3858` and `9755` are both being pulled in when importing jQuery and have many children. These child chunks are what is showing up in the Statoscope report, although they are not used by the entry point `onboarding_startguide`. The trouble here is that I'm not sure why all of these chunks are being marked as children. They seem to be all 3rd party packages which we're using in other entry points. In addition, these are only identifiable by the module or chunk IDs and are specific to our project.
![image](https://user-images.githubusercontent.com/2090758/177573993-245b79e4-28c8-4a39-b0ea-86fc71502cc7.png)
![image](https://user-images.githubusercontent.com/2090758/177574072-10f3fc12-fe9b-4c36-a11e-beea3cb30e7c.png)
![image](https://user-images.githubusercontent.com/2090758/177574237-e78bc6f5-d772-440b-97e7-02ac2cfe00b1.png)

**Comment by smelukov** [comment]
@hyshka Could you try 5.22.1-alpha.1 ? :)

**Comment by smelukov** [comment]
Which assets exactly included into html on tableview? )

**Comment by hyshka** [comment]
The `tableview` would contain:
```
<script src="/static/bundles/runtime.5d784a2b8506267e699b.bundle.js" ></script>
<script src="/static/bundles/3858.66f3908b791245f8c592.bundle.js" ></script>
<script src="/static/bundles/9755.c2da9ff2c8cc9a06df5c.bundle.js" ></script>
<script src="/static/bundles/7963.4b2130295c9a9ad5abb9.bundle.js" ></script>
<script src="/static/bundles/144.3ba4cdce77e3138b7786.bundle.js" ></script>
<script src="/static/bundles/984.36b30268b8d6b8e5a73f.bundle.js" ></script>
<script src="/static/bundles/6699.1f19460fee7ba0a969fc.bundle.js" ></script>
<script src="/static/bundles/629.0f567b86f3792a489144.bundle.js" ></script>
<script src="/static/bundles/178.78bc5cbaa67ca0c5b4c7.bundle.js" ></script>
<script src="/static/bundles/6950.92428004a9ebe30e7b00.bundle.js" ></script>
<script src="/static/bundles/7907.2a1100728c580ed88771.bundle.js" ></script>
<script src="/static/bundles/3331.98ab1754fbb38e2267cb.bundle.js" ></script>
<script src="/static/bundles/tableview.b4008db71d963a76e398.bundle.js" ></script>
```

This is another page where we use multiple entry points so in the HTML we would also include these although Webpack is not aware.
```
<script src="/static/bundles/7915.495cf5511fe06a533f9d.bundle.js" ></script>
<script src="/static/bundles/muckrack.e00b28506927562b450e.bundle.js" ></script>
```

**Comment by smelukov** [comment]
Working on it )

**Comment by smelukov** [comment]
@hyshka how about 5.22.1-alpha.3 ? 😄

**onboarding_startguide**
![image](https://user-images.githubusercontent.com/6654581/178072682-57d86586-a363-4783-8dde-93f0c65caa0a.png)

**tableview**
![image](https://user-images.githubusercontent.com/6654581/178072742-caacd984-f0cc-405f-bee4-45365fb6d996.png)

**Comment by smelukov** [comment]
@hyshka
For example, let's look at the origins of chunk with id 144
`compilations.chunks.[id=144].origins`

![image](https://user-images.githubusercontent.com/6654581/178345695-e174168b-1fe2-4ba3-94cf-417b85c01c6e.png)
This module from `styleguide`-entrypoint
So, `styleguide`-entrypoint requires chunk with id 144. Chunk 144 is initial and contains `node_modules/vue/dist/vue.runtime.esm.js`

Note that `styleguide.chunks` != `all the initial chunks of the styleguide-entrypoint`.
Some chunks contain children chunks that is not listed in entrypoint's chunks

**Comment by smelukov** [comment]
```
<script src="/static/bundles/runtime.5d784a2b8506267e699b.bundle.js" ></script>
<script src="/static/bundles/3858.66f3908b791245f8c592.bundle.js" ></script>
<script src="/static/bundles/9755.c2da9ff2c8cc9a06df5c.bundle.js" ></script>
<script src="/static/bundles/7963.4b2130295c9a9ad5abb9.bundle.js" ></script>
<script src="/static/bundles/7915.495cf5511fe06a533f9d.bundle.js" ></script>
<script src="/static/bundles/styleguide.31cb7cd49690c21c7a1c.bundle.js" ></script>
```

If webpack does not include chunk 144 into your page as initial then it's strange.
Either webpack has a bug with chunk including or stats generation :)

**Comment by hyshka** [comment]
@smelukov Thanks for taking a look at that, this covers everything within Statoscope for me than! Thanks so much for your help in resolving this, it is really appreciated. I am really enjoying Statoscope.

Both of my modules where this chunk is used load it async, so it seems like Webpack should not be marking chunk 144 as initial. I can confirm that chunk 144 is not loaded except for the pages which pull it in asynchronously. I will investigate this separately or report the bug to Webpack.

![image](https://user-images.githubusercontent.com/2090758/178367627-51867d29-78f7-405b-97d5-52a2f2c64012.png)

**Comment by smelukov** [comment]
@hyshka Thanks for your issue and for your help. It made Statoscope better ☺️
I'm going to publish a stable version with chunk relations fix
