### ISSUE TITLE
Package's modules not display in packages view or modules's view

### ISSUE THREAD

**Issue by icy0307** [statoscope/statoscope#194]
**Describe the bug**
Package's modules no display in Packages view

**To Reproduce**
1. Download this [stats.json](https://gist.github.com/icy0307/75397da3637c3f8d4591d87b26b034a5)
    This comes from a mini demo, which only has a simple import statement in the entry file.
``` ts
import { add } from 'lodash-es';
console.log(add);
```
2. `npx statoscope validate --input stats.json`

**Current behavior**
'lodash-es' 's modules neither display in modules' view or in the package's view
<img width="852" alt="image" src="https://user-images.githubusercontent.com/8952410/208016946-c9e75eb6-12a1-45fe-b4dd-04ac871a8371.png">

**Expected behavior**
Package's modules display in both packages view and modules's view

**Screenshots**
I tired debug myself, but have some trouble understanding jora's code.
But found that before jora's query, modules seems can be found in the compilation object.
<img width="2501" alt="image" src="https://user-images.githubusercontent.com/8952410/208018090-6af6a763-982e-4d32-bbfc-4e3c8a18279c.png">
**Versions**:
 - Node (for non-browser bug): 14.15.0
 - Browser (for browser-bug): 
 - Webpack: 5.38.1
 - Statoscope: 5.24.0

**Additional context**
I notice there are huge differences between  demo's  [stats.json](https://statoscope.tech/demo-stats.json)
and mine which also generate via  ` webpack --json stats.json`.
Again thx for this awesome library!

**Comment by smelukov** [comment]
@icy0307 👋
Hmmm, I can't reproduce this bug. Do you have any ideas what could I do, to reproduce it?

![2023-02-17_11-14-36](https://user-images.githubusercontent.com/6654581/219590709-a6207282-1adf-4d42-8c22-60f5902df056.png)

**Comment by icy0307** [comment]
Sorry, I can't reproduce it either now.
I will close this issue and reopen it if I can find the way. Thx for your effort.
