### ISSUE TITLE
The page stucked when module. nameForCondition is too longer.

### ISSUE THREAD

**Issue by huangchen1031** [statoscope/statoscope#200]
**Describe the bug**
The page stucked when module. nameForCondition is too longer.

**To Reproduce**
1. Just upload my stats.json

**Expected behavior**
None.

**Screenshots**
![image](https://user-images.githubusercontent.com/16714412/212291470-6554a545-2f74-4e7c-8114-97d039bf9bee.png)

**Versions**:
 - Node (for non-browser bug): 
 - Browser (for browser-bug): 
 - Webpack: 5.74.0
 - Statoscope: latest

**Additional context**
I think the problem is cost too many time at RegExp.
![image](https://user-images.githubusercontent.com/16714412/212292769-dfd54770-d743-489a-ab3a-21e773714573.png)
When I changed some code, the page can worked.
<img width="407" alt="image" src="https://user-images.githubusercontent.com/16714412/212292180-f05a89dc-8198-4a08-8cba-974a346a935d.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/16714412/212292211-fc2a2345-79ed-4230-8bda-3fa9992d109e.png">
<img width="527" alt="image" src="https://user-images.githubusercontent.com/16714412/212292264-3bbc2368-ecf5-4f31-b271-34f2488ed558.png">

**Comment by smelukov** [comment]
Thanks for the issue!
I'll fix it in the nearest release
