### ISSUE TITLE
Is statoscope working with Create-React-App and craco

### ISSUE THREAD

**Issue by rsurkin** [statoscope/statoscope#208]
**Describe the bug**

It's more about question: Is statoscope working with Create-React-App and craco

**To Reproduce**
1.  create new project with  npx create-react-app my-app
2. install craco (alternative to eject)  npm i -D @craco/craco 
3. install plugin  npm i -D @statoscope/webpack-plugin 
3. create simple config 
craco.config.js
```
const StatoscopeWebpackPlugin = require('@statoscope/webpack-plugin').default


module.exports = {
  webpack: {
    plugins: [
      new StatoscopeWebpackPlugin(),
    ]
  },
};
```
4. run npm run build

got 

```Seems like this is an empty compilation```

**Expected behavior**
See magnificent statoscope report 

**Screenshots**

**Versions**:
 - Webpack:  "webpack": "^5.87.0",
 - Statoscope: "@statoscope/webpack-plugin": "^5.26.2"

**Additional context**

I've also tried to eject config, comment all plugins, and add only, new StatoscopeWebpackPlugin(),
nothing changed in report

**Comment by RettentoRectangle** [comment]
Same was here.
Try this:
statsOptions: { all: true, source: false }

**Comment by cmdcolin** [comment]
I have an ejected CRA and ran into this error


```
Cannot read properties of undefined (reading 'tap')
```

didnt investigate carefully as there was no other output but just another data point
