### ISSUE TITLE
Add compress option to `@statoscope/stats-report` to avoid large html

### ISSUE THREAD

**Issue by icy0307** [statoscope/statoscope#209]
**Is your feature request related to a problem? Please describe.**
Thx for the awesome library!
I use statoscope cli with validator, and the report   `@statoscope/stats-validator-reporter-stats-report` is over 500MB.
So it it quiet hard to upload it to cos on the cli

**Describe the solution you'd like**
A compress option so it can compress the HTML like `--no-compression` did.

**Describe alternatives you've considered**

**Additional context**

**Comment by smelukov** [comment]
closed by #210
