### ISSUE TITLE
Add output for statoscope validate cli

### ISSUE THREAD

**Issue by kalagin** [statoscope/statoscope#222]
**Is your feature request related to a problem? Please describe.**

When i start statoscope validate in CI/CD:
```sh
statoscope validate --input webpack-stats.json
```
if something went wrong (build not valid) i see warn/error and its cool, but if we dont have warn/error - i dont know current mertrics for e.g @statoscope/webpack/build-time-limits value

**Describe the solution you'd like**

i want to see output after call validate:
```sh
statoscope validate --input webpack-stats.json
# output in console:
{
  build-time: 74,
  entry-download-time: 30,
  # ...etc
}
```

**Describe alternatives you've considered**
no

**Additional context**

its really usable for calibration rules and we can create some beautiful report when using in CI/CD jobs

**Comment by smelukov** [comment]
Hi! You can use [statoscope query](https://github.com/statoscope/statoscope/tree/master/packages/cli#query) for that.
And [here is some example](https://github.com/statoscope/statoscope.tech/blob/main/.github/workflows/ci.yml#L56)

**Comment by kalagin** [comment]
thanks you!
