### ISSUE TITLE
Stats diff feature in webpack plugin does not work as expected

### ISSUE THREAD

**Issue by zubair-bashir** [statoscope/statoscope#227]
@smelukov 

I'm trying to generate the JSON stats on every build and a single report file that is loaded with previous stats so that I can run a diff across the different builds' stats data. Here's the structure I'm aiming for. One report file which is loaded with other reports data on every new build:

<img width="350" alt="image" src="https://github.com/statoscope/statoscope/assets/89123863/372b0a37-3e51-4b07-ad02-701a44feccad">

Here's my config based on **fs** node module as opposed to glob in the docs. Is it only supposed to work with glob?

<img width="992" alt="image" src="https://github.com/statoscope/statoscope/assets/89123863/5bef11d9-abb1-4a68-898f-bb237f8cb877">

The JSON stats are generated correctly and so is the HTML report file which over-rides the earlier on every build with the same name. But when opening the report file I only get the first build's stats even though the other builds' content is correctly present inside the report HTML file.

I can only see the first compilation in the index section but report section correctly identifies both:
<img width="1670" alt="Screenshot 2023-12-17 at 11 29 27 PM" src="https://github.com/statoscope/statoscope/assets/89123863/d8ad2dd4-2930-4162-a803-b2aeb7b50a9b">

<img width="1670" alt="Screenshot 2023-12-17 at 11 28 11 PM" src="https://github.com/statoscope/statoscope/assets/89123863/1dd77e6c-948c-4828-b7fa-69e6e2af1360">

Debugged wether a correct array of earlier paths is being fed correctly into the plugin and yeah it is but still the same behaviour. So for a newer build being run for the directory structure above here's the **additionalStats** option being set:

<img width="685" alt="Screenshot 2023-12-17 at 11 19 11 PM" src="https://github.com/statoscope/statoscope/assets/89123863/4bda6183-620c-4d03-8c3c-b5743e57732d">

Statoscope Version: 5.28.2
Webpack Version: 4.28.3

Any idea what might be happening here.

**Comment by zubair-bashir** [comment]
My bad, I was trying to test the plugin implementation by generating multiple builds of the same code and apparently if statoscope finds that it's the same stats it does not list them distinctly for diffing. I guess this comment could be made available in the docs to avoid any confusion.

**Comment by smelukov** [comment]
Hi! Yep, there is a case when compilation hashes are the same. In the next major update this part will be refactored to use filename + hash instead of hash

**Comment by trigolos** [comment]
@smelukov 
It looks like the bug is still reproducible on version 5.28.3. 
If we generate a diff report and hash will be the same (code without changes), we will see only first compilation on the main page. No option to specify a second compilation.
At the same time, the "Make report" page displays both compilations.
