### ISSUE TITLE
https:// certificate expired for the webpage 

### ISSUE THREAD

**Issue by praveen-zensar** [statoscope/statoscope#228]
**Describe the bug**
Website https certificate is expired. Make it to auto. 

**To Reproduce**
1. Go to https://statoscope.tech/
2. See error message

**Expected behavior**
Must be valid https certificate.
**Screenshots**
<img width="274" alt="image" src="https://github.com/statoscope/statoscope/assets/152613575/720281b2-a805-41de-827e-80dee2bd308e">

**Comment by smelukov** [comment]
Thanks! I've just updated the certificate
