### ISSUE TITLE
Statoscope Validation Error Due to False Detection of Version Duplicates in Angular Project with Module Federation Configuration

### ISSUE THREAD

**Issue by MuTaToR08** [statoscope/statoscope#230]
**Describe the bug**
When adding a package to `shared` for Module Federation in an Angular project, validating the build with Statoscope fails with an error indicating that there are duplicates of the same version. This issue arises specifically when trying to manage shared dependencies in a microfrontend architecture using Module Federation.

**To Reproduce**

1 .Clone the repository from https://github.com/MuTaToR08/statoscope-duplicate
2. Run `npm run statoscope` in the project directory.

**Expected behavior**
The expected outcome is for Statoscope to validate the build without reporting errors regarding duplicate versions of the same package. The tool should recognize shared packages configured for Module Federation without flagging them as duplicates.

**Screenshots**
![image](https://github.com/statoscope/statoscope/assets/8342939/49cec100-1227-4ea2-baf6-d4f2bcd397fc)

**Versions**:
 - Node v20.11.1
 - Webpack: 5.90.1
 - Statoscope: 5.28.2

**Additional context**
This issue appears to be related to how Statoscope interprets the configuration for shared dependencies in Module Federation setups. It may misidentify the shared package versions as duplicates even when they are correctly configured for sharing across different parts of a microfrontend architecture. The duplicates in question are not actual redundant copies of the package but are intended configurations for sharing the package across microfrontends, which should not be flagged as errors. This misinterpretation by Statoscope can mislead developers into thinking there's an issue with their package management or build configuration, potentially leading to unnecessary troubleshooting and confusion about the integrity of the build process.

**Comment by smelukov** [comment]
Hi! Thanks for the issue! I'll deal with it 👌

**Comment by smelukov** [comment]
fixed in 5.28.3
