### ISSUE TITLE
website is down: statoscope.tech

### ISSUE THREAD

**Issue by EvanLovely** [statoscope/statoscope#231]
The site, https://statoscope.tech, does not load. Where are docs?

**Comment by fvsch** [comment]
Looks like a certificate error (or a domain routing issue).

![Screenshot 2024-03-19 at 20 05 04](https://github.com/statoscope/statoscope/assets/243601/e888d829-e14e-419f-9198-43fca64a3f38)

**Comment by Golodhros** [comment]
Is there a way to run this in our local?

**Comment by smelukov** [comment]
> Is there a way to run this in our local?

yep, you could use statoscope cli:

```sh
npx @statoscope/cli generate -i path/to/stats.json -o
```
This one will generate an html-report and open it in your browser

**Comment by smelukov** [comment]
I've finally solved all the issues with statoscope-hosting

**Comment by jakub-g** [comment]
FWIW, same issue today - the TLS cert has expired on Feb 8
