### ISSUE TITLE
[Request]: Use as a CLI Utility or Node API

### ISSUE THREAD

**Issue by SimulatedGREG** [statoscope/statoscope#51]
Similar to `webpack-bundle-analyzer`'s setup https://github.com/webpack-contrib/webpack-bundle-analyzer#usage-as-a-cli-utility, would it be possible to setup the same functionality here? 

The closest thing I can do to achieve this is to setup a bare webpack configuration, add the statoscope plugin and pass in my stat files via the `additionalStats` option.

It would be fantastic if there was a CLI method or even a Node API to quickly input already saved stats and start a local server of the UI.

Thank you for the considerations! This is such an awesome tool!

**Comment by smelukov** [comment]
Hi. Sorry for the answer delay
Yep, I'm working on a huge improvement that'll make it possible to run statoscope as a CLI tool (and some secret features ;))

**Comment by smelukov** [comment]
@SimulatedGREG done with it in v5 😄 
Now you can:
`statoscope serve path/to/stats.json`

Also, you can **validate** your stats via CLI 🎉 

Please, see [@statoscope/cli](https://github.com/statoscope/statoscope/blob/v5.0.0/packages/cli/README.md) for more info

**Comment by smelukov** [comment]
Also note, that now you should use `@statoscope/webpack-plugin` package instead of `@statoscope/ui-webpack`

**Comment by SimulatedGREG** [comment]
Thank you so much @smelukov!
