### ISSUE TITLE
Broken links at statoscope.tech

### ISSUE THREAD

**Issue by mrtheyann** [statoscope/statoscope#65]
Yo, I was going to fix these links in the repo, but it looks like these markups are served directly from a server as an html document (or maybe I had not dive deep enough into monorepo to find them) 

![image](https://user-images.githubusercontent.com/15281217/120226234-3ebaa380-c260-11eb-8b48-1dd9f219a23c.png)

Anyway, replace `ui-webpack` to `webpack-ui`. That will help to fix 404s for the most cases.

i.e:
`https://github.com/statoscope/statoscope/tree/master/packages/ui-webpack#which-stats-flags-statoscope-use`
to
`https://github.com/statoscope/statoscope/tree/master/packages/webpack-ui#which-stats-flags-statoscope-use`

Have a nice day up there.

**Comment by smelukov** [comment]
Thanks! Fixed

> markups are served directly from a server as an HTML

Yep, I'll move to this repo soon
