### ISSUE TITLE
Statoscope plugin fails in childCompilation for workbox-webpack-plugin.InjectManifest

### ISSUE THREAD

**Issue by budarin** [statoscope/statoscope#84]
**Describe the bug**
try to use statoscope for workbox-webpack-plugin.InjectManifest and it doesn't work
most of the problems in workbox-webpack-plugin.InjectManifest are related to plugin problems in childComplilation - maybe this also applies to the plugin 

**To Reproduce**
1. Add workbox-webpack-plugin.InjectManifest plugin into a webpack config

```js
plugins: [ 
        new InjectManifest({
            swSrc: './src/sw.js',
            swDest: 'sw.js',
            webpackCompilationPlugins:
                [
                      new StatoscopeWebpackPlugin({
                          name: 'SW',
                          saveTo: path.resolve(`./dist/sw-statoscope.html`),
                          open: 'file',
                      }),
                  ]
        }),
```
2. start webpack to build
4. See the absense of a statoscope's report

**Expected behavior**
Expected to see a report for service worker

https://developers.google.com/web/tools/workbox/reference-docs/latest/module-workbox-webpack-plugin.InjectManifest

**Versions**:
 - Node (for non-browser bug): 16.0.0
 - Statoscope: ^4.1.2

**Comment by smelukov** [comment]
Hello.
I had tried to use this:
```js
new InjectManifest({
            swSrc: './src/sw/sw.js',
            swDest: 'sw.js',
            webpackCompilationPlugins:
                [
                      new StatoscopeWebpackPlugin({
                          name: 'SW',
                          saveTo: path.resolve(`./dist/sw-statoscope.html`),
                          open: 'file',
                      }),
                  ]
        }),
```
Then `npm run build`
And there is no problem. HTML report with two compilations was successfully generated.

![image](https://user-images.githubusercontent.com/6654581/124365896-e65a3580-dc53-11eb-987b-5a6e7f443fec.png)
![image](https://user-images.githubusercontent.com/6654581/124365906-f70aab80-dc53-11eb-9b8e-b058822c5124.png)

**Comment by smelukov** [comment]
Please, ensure that child compilations are not hidden
![image](https://user-images.githubusercontent.com/6654581/124365942-523c9e00-dc54-11eb-9aab-63d2d62f4d7a.png)

**Comment by budarin** [comment]
I'm sorry - I constantly forget about this option and this is not immediately visible in the report

**Comment by smelukov** [comment]
@budarin Please note that Statoscope is 5.4.1 now ;)
Consider updating for more features (stats validation on CI, gzip-sizes, packages version) ☺️

**Comment by budarin** [comment]
thanks !
