### ISSUE TITLE
Remove autoupgrade dependencies in @statoscope/webpack-plugin

### ISSUE THREAD

**Issue by amaxalov** [statoscope/statoscope#88]
**Describe the bug**
If the project is highly loaded, no one will update the main plugin every time, but its dependencies are constantly updated, which are incompatible with the main version.

**Screenshots**
![image](https://user-images.githubusercontent.com/15657131/125315706-6e24fb80-e348-11eb-849f-427a8be80cbf.png)

**Versions**:
 - Node (for non-browser bug): 14.10
 - Browser (for browser-bug): any
 - Statoscope: 5.4.8

**Additional context**

**Comment by smelukov** [comment]
Now I use `exact: true` in lerna config
