### ISSUE TITLE
Options to extend statoscope report

### ISSUE THREAD

**Issue by lizryzhko** [statoscope/statoscope#92]
**Is your feature request related to a problem? Please describe.**

Hi, I'm looking for a way to use the default statoscope report with additional data (not stats.json) and views.
As I see there are no options like that in the cli and webpack-ui. What do you think about adding this feature?

**Describe the solution you'd like**
I'd like to define a config for the cli and specify paths to stats.json and myData.json, jora helpers, queries, pages.

**Describe alternatives you've considered**
Also statoscope could provide a config with its views and data transformations for a separate new discovery.js instance.

**Comment by smelukov** [comment]
Hi. Thanks for the issue.
Yep, this feature is in plan and will be implemented soon, after I done another cool feature that I’m working on :)

**Comment by smelukov** [comment]
Release in v5.9
Please, see an [example](https://github.com/statoscope/statoscope/tree/master/packages/webpack-plugin#optionsreports-report) ☺️
